name: DB Schema Snapshot
on:
  workflow_dispatch:
  push:
    paths:
      - 'phisnet/migrations/**'
      - 'phisnet/server/**'
      - 'phisnet/shared/**'

jobs:
  dump-schema:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: phishnet
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -U postgres && break
            sleep 2
          done
      - name: Apply SQL migrations
        run: |
          set -e
          if [ -d phisnet/migrations ]; then
            for f in phisnet/migrations/*.sql; do
              [ -f "$f" ] && psql -h localhost -U postgres -d phishnet -f "$f"
            done
          fi
      - name: Dump schema snapshot
        run: |
          mkdir -p phisnet/docs/db
          pg_dump -h localhost -U postgres -d phishnet -s > phisnet/docs/db/schema.sql
      - name: Commit snapshot if changed
        run: |
          if ! git diff --quiet phisnet/docs/db/schema.sql; then
            git config user.name "schema-bot"
            git config user.email "schema-bot@users.noreply.github.com"
            git add phisnet/docs/db/schema.sql
            git commit -m "chore(db): update schema snapshot"
            git push
          else
            echo "No schema changes detected"
          fi
