# .github/quality-gates.yml
# PhishNet Quality Gates Configuration
# This file defines quality standards and gates for the codebase

quality_gates:
  # Code quality thresholds
  code_quality:
    eslint:
      max_warnings: 10
      max_errors: 0
      required_rules:
        - "no-console"
        - "no-debugger"
        - "prefer-const"
    
    typescript:
      strict_mode: true
      no_implicit_any: true
      no_unused_locals: true
    
    complexity:
      max_cyclomatic_complexity: 10
      max_function_length: 50
      max_file_length: 500
  
  # Security gates  
  security:
    vulnerability_scanning:
      max_critical: 0
      max_high: 2
      max_medium: 10
    
    dependency_check:
      outdated_packages: true
      security_advisories: true
      license_compliance: true
    
    secrets_detection:
      enabled: true
      block_on_detection: true
  
  # Performance gates
  performance:
    bundle_size:
      max_main_bundle: "2MB"
      max_vendor_bundle: "1MB"
    
    lighthouse:
      min_performance_score: 80
      min_accessibility_score: 90
      min_best_practices_score: 85
      min_seo_score: 80
    
    load_time:
      max_first_contentful_paint: "2s"
      max_largest_contentful_paint: "4s"
  
  # Test coverage gates
  testing:
    unit_tests:
      min_coverage: 80
      min_line_coverage: 85
      min_branch_coverage: 75
    
    integration_tests:
      required: true
      min_scenarios: 10
    
    e2e_tests:
      required: true
      critical_paths: true
  
  # Documentation gates
  documentation:
    readme:
      required: true
      sections:
        - "Installation"
        - "Usage"
        - "API Documentation"
        - "Contributing"
    
    api_docs:
      coverage: 90
      format: "OpenAPI"
    
    code_comments:
      min_coverage: 60
      required_for_public_methods: true

# Enforcement settings
enforcement:
  strict_mode: true
  fail_fast: false
  notification_channels:
    - github_checks
    - pull_request_comments
  
  exemptions:
    emergency_deployments: false
    hotfix_branches: true
    
# Gate evaluation order
evaluation_order:
  - security
  - code_quality  
  - testing
  - performance
  - documentation
