# .github/security-config.yml
# PhishNet Security Configuration
# This file defines security settings for branch protection and monitoring

security:
  enabled: true
  
  # Branch protection settings
  branch_protection:
    enforce_admins: true
    required_status_checks:
      strict: true
      contexts:
        - "CI Pipeline"
        - "Security Scanning"
        - "Quality Gates"
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
    restrictions:
      enforce_for_admins: false
  
  # Security checks configuration  
  checks:
    - branch_protection
    - dependency_scanning
    - code_scanning
    - secret_scanning
    
  # Vulnerability scanning
  vulnerability_scanning:
    enabled: true
    schedule: "daily"
    severity_threshold: "medium"
    
  # Access control
  access_control:
    require_signed_commits: true
    allow_force_pushes: false
    allow_deletions: false
    
  # Monitoring settings
  monitoring:
    alerts_enabled: true
    notification_channels:
      - email
      - github_notifications
    
  # Compliance requirements
  compliance:
    soc2: true
    gdpr: true
    cybersecurity_framework: true
