# Branch Protection Configuration
# Enforces security and quality standards for main branch

name: "PhishNet Branch Protection"
description: "Enterprise-grade branch protection for secure development"

branch_protection:
  main:
    # Require pull request reviews
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      dismiss_review_on_push: true
      
    # Require status checks
    required_status_checks:
      strict: true
      checks:
        - "ci/tests"
        - "ci/security-scan"
        - "ci/quality-gates"
        - "ci/build"
        
    # Additional protections
    enforce_admins: false
    allow_force_pushes: false
    allow_deletions: false
    required_conversation_resolution: true
    
    # Restrict push access
    restrictions:
      users: []
      teams: ["developers", "maintainers"]
      apps: ["github-actions"]

# Development branch protections      
development_branches:
  "feature/*":
    required_status_checks:
      strict: false
      checks:
        - "ci/tests"
        - "ci/security-scan"
        
  "hotfix/*":
    required_status_checks:
      strict: true
      checks:
        - "ci/tests"
        - "ci/security-scan"
        - "ci/quality-gates"

# Security settings
security:
  require_signed_commits: true
  block_push_with_secrets: true
  vulnerability_alerts: true
  security_updates: true
